// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOcDQnXoxYWb0WxaK48RRaiwZR9-uZRA',
    appId: '1:31659431963:web:15dabb02967fdf1ce500be',
    messagingSenderId: '31659431963',
    projectId: 'utmcar-62352',
    authDomain: 'utmcar-62352.firebaseapp.com',
    storageBucket: 'utmcar-62352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfl_EE991ZdXr55xukvh5hmZPhid7RQY',
    appId: '1:31659431963:android:da6f382430ce334be500be',
    messagingSenderId: '31659431963',
    projectId: 'utmcar-62352',
    storageBucket: 'utmcar-62352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfEVKrx7dvd5MmG92dYhsaBfeLKB1vBWg',
    appId: '1:31659431963:ios:dd73844d099ecf36e500be',
    messagingSenderId: '31659431963',
    projectId: 'utmcar-62352',
    storageBucket: 'utmcar-62352.appspot.com',
    iosBundleId: 'com.example.projectcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfEVKrx7dvd5MmG92dYhsaBfeLKB1vBWg',
    appId: '1:31659431963:ios:a897279f34cc9b4ee500be',
    messagingSenderId: '31659431963',
    projectId: 'utmcar-62352',
    storageBucket: 'utmcar-62352.appspot.com',
    iosBundleId: 'com.example.projectcar.RunnerTests',
  );
}
